# -*- coding: utf-8 -*-
"""Aula 01 - Tipos de Dados e Operadores Aritméticos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17TBbttGWRIt3UaGn_ktdp2K4Xrb18LkN

<img src="https://www.cesar.school/wp-content/uploads/2019/09/marca_cesar_school.png" alt="drawing" width="200"/>

# Python - **Aula 01**

---

- Markdown
- Entender conceitos básicos sobre programação;
- Conhecer a linguagem Python;
- Variáveis;
- Tipos de dados;
- Manipulação de strings.

# Colab e Markdown

O Colab possui dois tipos de células: **código** e **texto**.

Nas células de código, você pode programar e executar os scripts usando Python.

Nas células de texto é possível usar a linguagem de marcação [Markdown](https://daringfireball.net/projects/markdown/syntax). Você pode consultar alguns guias sobre o uso do Markdown nesses links:
- https://colab.research.google.com/notebooks/markdown_guide.ipynb
- https://docs.pipz.com/central-de-ajuda/learning-center/guia-basico-de-markdown#open

# Introdução à variáveis

Em termos técnicos, uma variável atribui um local de armazenamento na memória a um valor que está vinculado a um nome ou identificador simbólico. O nome da variável é usado para fazer referência a esse valor armazenado em um programa de computador.
"""

my_int = 103204934813

"""*   o nome da variável `my_int`
*   o operador de atribuição, também conhecido como sinal de igual `=`
*   o valor que está sendo vinculado ao nome da variável `103204934813`

Em Python, a declaração de uma variável é feita apenas no momento de sua atribuição, não sendo necessário definir explicitamente seu tipo.

## Regras para criação de nomes de variáveis:

- Não pode começar com número;
- Não pode haver espaço (use `_`);
- Não pode haver caracteres especiais: `" ' , < > | / \ ( ) @ ! # $ % ^ & * ~ - +`

##Reatribuindo Variáveis
"""

nome_composto = "Gerson"
nome_composto = 20
nome_composto = 50
nome_composto = 29.4
nome_composto = "Novo Gerson"
nome_composto = 58.263725

"""# `print()`

Exibe o valor de uma ou várias variáveis.

```python
print('exemplo')
print('exemplo', 'vários', 'valores')
print(variavel1, variavel2, variavel3)
```

"""

print("Olá Mundo!")
print(nome_composto, my_int, 384, 19.5, "Gerson")
print(my_int)

"""##Atribuição múltipla

Com Python, você pode atribuir um único valor a várias variáveis ​​ao mesmo tempo. Isso permite inicializar várias variáveis ​​de uma vez, que você mesmo pode reatribuir posteriormente no programa ou por meio da entrada do usuário.

```python
x = y = z = 0
```

Outra possibilidade, é atribuir vários valores diferentes para variáveis específicas.

```python
x, y, z = 10, 15, 20
```
"""

x = y = z = 0

x = 0
y = 0
z = 0

x, y, z = 10, 15, 20

x = 10
y = 15
z = 20

print(x)
print(y)
print(z)

"""
#Criação e impressão de strings

Textos (strings) existem entre aspas simples `'` ou duplas `"` em Python, portanto, para criar uma string, coloque uma sequência de caracteres em um ou outro.

```python
s1 = 'Esta é uma string entre aspas simples.'

s2 = "Esta é uma string entre aspas duplas."

s3 = '''Essa é uma string
entre aspas triplas'''
```

Podemos imprimir strings simplesmente chamando a função `print()`"""

s1 = 'Esta é uma string entre "aspas" simples.'

s2 = "Esta é uma string entre 'aspas' duplas."

s3 = '''Essa é uma string
entre aspas triplas simples'''

s4 = """Essa é uma string
entre aspas triplas duplas"""

"""## Sintaxe do comentário

Para escrever comentários em Python usamos o caractere de hash `#`. Tudo o que estiver escrito a direita dele será ignorado até o fim da linha.

```python
# comentário de linha
```

É possível ainda escrever um bloco de comentário usando "aspas triplas":
```python
'''exemplo de
comentário
em várias linhas'''
```

### Comentários inline
Os comentários *inline* ocorrem na mesma linha de uma instrução, seguindo o próprio código.

Geralmente, os comentários inline são assim:

```python
x = 8 # a variável x recebe 8 👍
```
"""

nome = "Gerson" # esta variavel armazena um nome
print(nome)

nome = "Gerson"
"""
esta variavel
armazena um nome
"""
print(nome)

"""# Tipos de dados

É possível exibir os tipos de um valor ou variável usando a função `type()`.

## Numéricos
- `int` - Inteiros
- `float` - Pontos Flutuantes

## Texto
- `str` - String

## Booleano
- `bool` - `True` ou `False`

## Listas
- `list` - [ ]

## Sets
- `set` - { }

## Tuplas
- `tuples` - ( )

## Dicionários
- `dictionary` - { }
"""

inteiro = 28
altura = 1.83
texto = "Olha só"
exemplo = "10"
b1 = True
b2 = False

"""A flexibilidade da tipagem dinâmica é conseguência de duas estratégias implementadas na linguagem:
- A primeira é conhecida como **Duck Typing**:
> "Se anda como pato, nada como um pato e faz quack como um pato, então provavelmente é um pato"

- A segunda é a abordagem **EAFP**:
> "*It is Easier to Ask for Forgiveness than Permission*"
>
> "É melhor pedir desculpas do que pedir permissão"
>
> [Grace Hopper](https://en.wikipedia.org/wiki/Grace_Hopper)
"""

# Exibir os tipos dos dados usando a função type()
inteiro = 28
print(type(inteiro))
altura = 1.83
print(type(altura))
texto = "Olha só"
print(type(texto))
exemplo = "10"
print(type(exemplo))
b1 = True
print(type(b1))
b2 = False
print(type(b2))

"""# Entrada de Dados
Entrada de dados refere-se ao recebimento de informações do mundo externo para o meio digital.

Em Python, pode ser feito usando a função `input()`.

Sintaxe da função:

```python
variavel = input('mensagem opcional')
```

*Obs.: Os dados recebidos do input são sempre `str`.*
"""

entrada = input("Insira a sua idade: ")
print(type(entrada))
print("Valor inserido pelo usuário: ", entrada)

"""#Funções para conversão de tipo

Algumas vezes é necessário converter valores de um tipo para outro. Em Python, todos os tipos possuem contrutores que podem ser usados para **tentar** converter dados de um formato para outro.

```python
int()
float()
bool()
str()
```

##Convertendo os tipos de número
"""

# int → float
num1 = 10
num2 = float(num1)
print(type(num1))
print(type(num2))
# float → int

num4 = int(10.518726781)
print(type(num4))
print("int: ", num4)

# bool → int
# True = 1
# False = 0
num5 = int(False)
print(type(num5))
print("int: ", num5)

# str → int

num6 = int("56786")
print(type(num6))
print("int: ", num6)

# str → float

num7 = float("56786.1873812")
print(type(num7))
print("float: ", num7)

# str → bool

num8 = bool("True")
print(type(num8))
print("bool: ", num8)

# int → str

num9 = str(1245)
print(type(num9))
print("string: ", num9)

# float → str

# bool → str

"""# Operações Aritméticas

Em Python as 4 operações aritméticas básicas são feitas usando os tradicionais operadores `+`, `-`, `*` e `/`.

- `x + y`:	Soma de x e y
- `x - y`:	Subtração de x e y
- `x * y`:	Multiplicação de x e y
- `x / y`:	Divisão de x e y (gerando sempre um valor *float*)

Os operadores de `+`  e `-` também podem ser usados para manipular o sinal do número:

- `+x`:	Identidade de x
- `-x`:	Sinal alterado de x

Python também dispõe de outros operadores :

- `x // y`:	Divisão inteira de x e y
- `x ** y`:	x elevado a y
- `x % y`:	Resto da divisão de x por y

"""

print(10 / 3)

"""## Precedência aritmética

A ordem das operações aritméticas em Python é semelhante a matemática e pode ser modificada com o uso de parênteses `()`

A precedência aritmética em Python segue a ordem:
1. `()`
2. `**`
3. `*`, `/` (*left-associative*)
4. `+`, `-` (*left-associative*)

```python
2 + 10 * 10 - 5 # 97
(2 + 10) * (10 - 5) # 60
```
"""

2 + 10 * 10 - 5 # 97

(2 + 10) * (10 - 5) # 60

"""##Operadores de atribuição

Podem ser usados para incrementar ou decrementar um valor.

* `+=` adiciona e atribui o valor
* `-=` subtrai e atribui o valor
* `*=` multiplica e atribui o valor
* `/=` divide e atribui o valor
* `//=` divide e depois atribuir o valor em inteiro
* `**=` aumentar a potência e então atribuir o valor
* `%=` retorna o resto da divisão e depois atribui o valor


"""

num = 10
num += 5
# num = num + 5
print(num)

"""# `str`

## str

Em Python, textos são armazenados como uma sequência de caracteres [Unicode](https://pt.wikipedia.org/wiki/Unicode). Essa seguência, conhecida como **String** é representada no Python com o tipo `str`.

[ASCII](https://www.ime.usp.br/~kellyrb/mac2166_2015/tabela_ascii.html)

Ex.: `'Exemplo de Texto'`

Por ser uma sequência, é possivel acessar cada caracter através de um índice. Além disso, o tipo `str` fornece uma variedade de métodos de manipulação desses caracteres.

Para criar uma variável `str`, é possível usar aspas simples, duplas ou "triplas":
"""

# Aspas simples
print('🤌')

# Aspas duplas


# Aspas triplas*

"""## Caracteres de Escape

São chamados de **caracteres de escape** marcadores usados para acessar caracteres do código Unicode. Para escreve-los, use `contra-barra + caractere`:

| sintaxe | descrição |
|---------|-----------|
| `\n` | Quebra de linha |
| `\t` | Tabulação |
| `\'` | Aspas simples |
| `\"` | Aspas duplas |
| `\\` | Contra-barra |

> Obs.: A interpretação dos caracteres de escape pode ser "desativada" usando Raw Strings, marcadas com um `r` antes das aspas:
```python
text = r'Exemplo de texto\nSem caracteres de escape'
```
"""

# caracteres de escape
print('Meu irmão é muito \'inteligente\'')
print("Meu irmão é muito 'inteligente'")

# r-strings
print(r'Meu irmão é muito \'inteligente\' \n nova linha')

"""## Função embutida `len()`

A função `len()` retorna a quantidade de itens dentro de um "container". Como as strings de Python são coleções de caracteres, a função `len()` quando recebe uma string, retorna a quantade de caracteres do texto.

```python
text = 'supercalifragilisticexpialidocious'
print(len(text)) # 34
```
"""

print(len("Gerson trabalha no CESAR!🤌"))

"""## str.find()

Retorna a posição de uma determinada substring procurada.

Se o valor retornado for:
- `>= 0` : Substring encontrado numa posição específica
- `< 0` : Substring não encontrado
"""

# grs@cesar.school
# 0123456789..
print("grs@cesar.school".find("s"))

"""## str.count()

Retorna a quantidade de ocorrências de determinada substring.
"""

texto = "grs@cesar.school"
print(texto.count("s"))

"""## Operações com Strings

> ⚠ Strings em Python são imutáveis, o que signifca que atribuir um valor a uma posição indexada irá resultar em um erro.

Os seguintes operadores podem ser usados com strings:

- `+` - Concatenação
- `*` - Repetição
"""

texto = "grs@cesar.school"
# texto[2] = "z" # não pode
print(texto[2])

print("homi" + " aranha")

print("miranha" * 10)

"""## str.lower() e str.upper()

- `.lower()` - Retorna uma nova string com caracteres em minúsculo
- `.upper()` - Retorna uma nova string com caracteres em maiúsculo
"""

nome = "Gerson"
print(nome.lower())
print(nome.upper())

"""## f-Strings

> formatted string literals

```python
name = 'Gerson'
print(f'Meu nome é {name}')
```

Mais detalhes sobre f-Strings [aqui](https://realpython.com/python-f-strings/).
"""

nome = "Gerson"
valor = 50

print("Meu nome é: ", nome, ", o Valor é: ", valor)
print("Meu nome é: " + nome + ", o Valor é: " + str(valor))
print(f"Meu nome é: {nome}, o Valor é:  {valor}")

"""## str.split()

Retorna uma lista de substrings dividido por um separador. Se nenhum parâmetro for passado, o separador (ou delimitador) adotado é o espaço em branco.
"""

numeros = '10 20 30'
print(numeros.split())
a, b, c = numeros.split()
print(a, b, c)

"""## str.replace()

Retorna uma nova string com um texto substituído por outro.

```python
str.replace('old', 'new')
```
"""

txt = "Geralt é um Witcher famoso."
print(txt.replace("Geralt", "Geraldo").replace("Witcher", "Bruxo"))

"""# Exercícios Fundamentais

1. Faça um programa que mostre a mensagem "*Alô mundo*" na tela
"""

print('Alô mundo')

"""2. Faça um programa que peça um número e então mostre a mensagem `O número informado foi [número]`."""

num = input('Informe um numero: ')
print('O numero informado foi:', num)

"""3. Faça um programa que peça dois números e imprima a soma."""

num1 = int(input('Informe um numero: '))
num2 = int(input('Informe outro numero: '))

print('Soma', num1 + num2)

"""4. Faça um programa que peça as 4 notas bimestrais e mostre a média."""

nota_1 = float(input("Digite a primeira nota: "))
nota_2 = float(input("Digite a segunda nota: "))
nota_3 = float(input("Digite a terceira nota: "))
nota_4 = float(input("Digite a quarta nota: "))

nota_final = (nota_1 + nota_2 + nota_3 + nota_4) / 4

print('A média é', nota_final)

"""5. Faça um programa que converta metros para centímetros."""

metros = float(input("Digite o tamanho em metros: "))

centimentros = metros * 100

print('Tamanho em centimetros é:', centimentros)

"""6. Faça um programa que peça o raio de um círculo, calcule e mostre sua área."""

r = float(input('Digite o raio do círculo: '))
pi = 3.14
area = (r**2) * pi
print('Area é ', area)

import math

r = float(input('Raio: '))
area = math.pi * math.pow(r, 2)
print(area)

"""7. Faça um programa que calcule a área de um quadrado, em seguida mostre o dobro desta área para o usuário."""

lado = int(input('Digite o lado do quadrado: '))
dobro_area = (lado**2)*2
print(f"Area é {dobro_area:.2f}")

"""8. Faça um programa que pergunte quanto você ganha por hora e o número de horas trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês."""

salario = float (input('Qual o seu salário por hora: '))
horas = float (input('Quantas horas você trabalhou no mês: ' ))

print ('Seu salário total no refererido mês é de {} '.format(salario * horas))

"""9. Faça um programa que peça a temperatura em graus Fahrenheit, transforme e mostre a temperatura em graus Celsius.

  $ °C = 5 \times ((°F-32) / 9) $

"""

f = float(input("Qual temperatura: "))
c = 5 * ((f-32)/9)
print(f"Temperatura é {c:.2f}")

"""10. Faça um programa que peça a temperatura em graus Celsius, transforme e mostre em graus Fahrenheit.

  $°F = (°C \times 9 / 5) + 32 $
"""

c = float(input("Qual temperatura: "))
f = c * 1.8 + 32
print(f"Temperatura é {f:.2f}")

"""11. Faça um programa que peça 2 números inteiros e um número real. Calcule e mostre:
- O produto do dobro do primeiro com metade do segundo.
- Soma do triplo do primeiro com o terceiro.
- Terceiro elevado ao cubo.
"""

num1 = int(input('Digite o primeiro número inteiro: '))
num2 = int(input('Digite o segundo número inteiro: '))
num3 = float(input('Digite um número real: '))

produto = (2 * num1) * (num2 / 2)
soma = 3 * (num1 + num3)
potencia_num = (num3**3)
print(f'Produto: {produto} | Soma: {soma} | Potência Cúbica: {potencia_num}')

"""12. Tendo como dados de entrada a altura de uma pessoa, construa um algoritmo que calcule seu peso ideal em Kg usando a seguinte fórmula:

  $ peso\_ideal = (72.7 \times altura) - 58 $
"""

altura = float(input('Digite sua altura: '))
peso = (72.7 * altura) - 58
print(f"Seu peso ideal é: {peso:.2f}")

"""13. Tendo como dado de entrada a altura ($h$) de uma pessoa, construa um algoritmo que calcule seu peso ideal, utilizando as seguintes fórmulas:
- Para homens: $ (72.7 \times h) - 58 $
- Para mulheres: $ (62.1 \times h) - 44.7 $
"""

h = float(input('Digite sua altura: '))

peso = (72.7 * altura) -58
print(f"O peso ideal para homem é: {peso:.2f}")
peso = (62.1 * altura) -44.7
print(f"O peso ideal para mulher é: {peso:.2f}")

"""14. Escreva um programa que substitui as ocorrencias de um caractere 0 em uma string por outro caractere 1."""

s = '010101'
print(s.replace('0', '1'))

"""15. Faça um programa que receba do usuario uma string. O programa imprime a string sem suas vogais."""

txt = input('Insira a string: ')
txt = txt.replace('a', '').replace('e', '').replace('i', '').replace('o', '').replace('u', '')

print(txt)

"""# Exercícios complementares

16. Faça um programa que pergunte quanto você ganha por hora e o número de horas trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês, sabendo-se que são descontados 11% para o Imposto de Renda, 8% para o INSS e 5% para o sindicato, faça um programa que nos dê:
    - salário bruto.
    - quanto pagou ao INSS.
    - quanto pagou ao sindicato.
    - o salário líquido.
    - calcule os descontos e o salário líquido, conforme a tabela abaixo:

```
            + Salário Bruto : R$
            - IR (11%) : R$
            - INSS (8%) : R$
            - Sindicato ( 5%) : R$
            = Salário Liquido : R$
```
> Obs.: Salário Bruto - Descontos = Salário Líquido.
"""

valor_hora = float (input('Digite qual o valor da sua hora de trabalho: '))
carga_horaria = float (input('Digite quantas horas você trabalhou esse mês: '))
salario_bruto = valor_hora * carga_horaria
ir = salario_bruto * .11
inss = salario_bruto * .08
sindicato = salario_bruto * .05
salario_liquido = salario_bruto - ir - inss - sindicato

print('O total do seu salário bruto nesse mês foi de R$ {}'.format(salario_bruto))
print('O total do valor recolhido para o IR nesse mês foi de R$ {}'.format(ir))
print('O total do valor recolhido para o INSS nesse mês foi de R$ {}'.format(inss))
print('O total do valor recolhido para o Sindicato nesse mês foi de R$ {}'.format(sindicato))
print('O total do seu salário liquido nesse mês foi de R$ {}'.format(salario_liquido))

"""17. Faça um programa que peça o tamanho de um arquivo para download (em MB) e a velocidade de um link de Internet (em Mbps), calcule e informe o tempo aproximado de download do arquivo usando este link (em minutos)."""

tamanho_arquivo = int(input('Digite quanto megabytes (MB) tem o arquivo para download: '))
velocidade_link = int(input('Digite qual a velocidade do link de internet em Mbps: '))
tempo_em_minutos = tamanho_arquivo / velocidade_link / 60
print(f'O tempo aproximado de download do arquivo usado neste link é de {tempo_em_minutos} min')

"""18. João Papo-de-Pescador, homem de bem, comprou um microcomputador para controlar o rendimento diário de seu trabalho. Toda vez que ele traz um peso de peixes maior que o estabelecido pelo regulamento de pesca do estado de São Paulo (50 quilos) deve pagar uma multa de R\$ 4,00 por quilo excedente. João precisa que você faça um programa que leia a variável peso (peso de peixes) e calcule o excesso. Gravar na variável excesso a quantidade de quilos além do limite e na variável multa o valor da multa que João deverá pagar. Imprima os dados do programa com as mensagens adequadas."""

peso = float(input('Qual valor de peso de peixes: '))
excesso = peso - 50
if excesso > 0:
  multa = excesso * 4
  print(f"João deve pagar R${multa:.2f} de multa")
else:
  print("João não irá precisar pagar multa")

"""19. Faça um programa para uma loja de tintas. O programa deverá pedir o tamanho em metros quadrados da área a ser pintada. Considere que a cobertura da tinta é de 1 litro para cada 3 metros quadrados e que a tinta é vendida em latas de 18 litros, que custam R\$ 80,00. Informe ao usuário a quantidades de latas de tinta a serem compradas e o preço total. Obs.: somente são vendidos um número inteiro de latas."""

# 1 litro de tinta --> 3 m²
# 1 lata de tinta --> 18 L
# 1 litro de tinta x lata de tinta --> 54 m²
# 1 lata de tinta = R$ 80.00

area_pintura = float (input('Digite quanto metros quadrados você deseja pintar: '))

if area_pintura % 54 == 0:
  qtd_latas = area_pintura//54
else:
  qtd_latas = area_pintura//54 + 1
preco_total = qtd_latas*80
print(f'Você precisará de {qtd_latas} latas. O valor total será de R$ {preco_total}'))

"""20. Faça um Programa para uma loja de tintas. O programa deverá pedir o tamanho em metros quadrados da área a ser pintada. Considere que a cobertura da tinta é de 1 litro para cada 6 metros quadrados e que a tinta é vendida em latas de 18 litros, que custam R\$ 80,00 ou em galões de 3,6 litros, que custam R\$ 25,00.
  - Informe ao usuário as quantidades de tinta a serem compradas e os respectivos preços em 3 situações:
  - comprar apenas latas de 18 litros;
  - comprar apenas galões de 3,6 litros;
  - misturar latas e galões, de forma que o desperdício de tinta seja menor. Acrescente 10% de folga e sempre arredonde os valores para cima, isto é, considere latas cheias.
"""

# Resolução

# 1 litro de tinta --> 6 m²

# 1 lata de tinta --> 18 L
# 1 litro de tinta x lata de tinta --> 108 m²
# 18L de tinta = R$ 80.00

# 1 lata de tinta --> 3,6 L
# 1 litro de tinta x lata de tinta --> 21,6 m²
# 3,6L de tinta = R$ 25.00

area_pintura = float (input('Digite quanto metros quadrados você deseja pintar: '))


# Apenas com lata de 18L
if area_pintura % 108 == 0:
  qtd_latas = area_pintura//108
else:
  qtd_latas = area_pintura//108 + 1
preco_total = qtd_latas*80
print(f'Você precisará de {qtd_latas} latas. O valor total será de R$ {preco_total}')

# Apenas com lata de 3.6L
if area_pintura % 21.6 == 0:
  qtd_latas = area_pintura//21.6
else:
  qtd_latas = area_pintura//21.6 + 1
preco_total = qtd_latas*25
print(f'Você precisará de {qtd_latas} latas. O valor total será de R$ {preco_total}')

area_pintura*=.1
lata_18 = area_pintura//108

area_pintura = area_pintura - (lata_18*108)
if area_pintura % 21.6 == 0:
  lata_3 = area_pintura//21.6
else:
  lata_3 = area_pintura//21.6 + 1

preco_total = lata_18*80 + lata_3*25

print(f'Você precisará de {lata_18} latas de 18L e {lata_3} latas de 3.6L. O valor total será de R$ {preco_total}')